/**
 * Mock Data Repository for Local Farmers Produce Direct-Selling Marketplace (Phase 5)
 * Structured with realistic Indian agricultural products, categories, farmer profiles, and reviews.
 */

export const MOCK_CATEGORIES = [
  {
    id: 'vegetables',
    name: 'Fresh Vegetables',
    description: 'Farm-fresh daily harvest vegetables grown with organic practices.',
    icon: 'Carrot',
    itemCount: 45,
    bgLight: '#e8f5e9',
    accentColor: '#2e7d32'
  },
  {
    id: 'fruits',
    name: 'Organic Fruits',
    description: 'Naturally ripened seasonal orchard fruits bursting with nutrition.',
    icon: 'Apple',
    itemCount: 32,
    bgLight: '#fff3e0',
    accentColor: '#e65100'
  },
  {
    id: 'grains',
    name: 'Grains & Cereals',
    description: 'Traditional unpolished whole grains, millets, and heirloom wheat.',
    icon: 'Wheat',
    itemCount: 18,
    bgLight: '#fef3c7',
    accentColor: '#b45309'
  },
  {
    id: 'leafy-greens',
    name: 'Leafy Greens',
    description: 'Crisp pesticide-free greens harvested early morning for maximum freshness.',
    icon: 'Sprout',
    itemCount: 22,
    bgLight: '#dcfce7',
    accentColor: '#15803d'
  },
  {
    id: 'dairy-eggs',
    name: 'Dairy & Farm Eggs',
    description: 'Pure A2 cow milk, churned ghee, butter, and free-range country eggs.',
    icon: 'Milk',
    itemCount: 14,
    bgLight: '#e0f2fe',
    accentColor: '#0369a1'
  },
  {
    id: 'pulses',
    name: 'Pulses & Legumes',
    description: 'Direct-from-farm unpolished dals, rich in plant protein.',
    icon: 'Layers',
    itemCount: 16,
    bgLight: '#fae8ff',
    accentColor: '#a21caf'
  },
  {
    id: 'honey-preserves',
    name: 'Raw Honey & Preserves',
    description: 'Pure unfiltered forest honeys and artisanal homemade fruit jams.',
    icon: 'Flower2',
    itemCount: 9,
    bgLight: '#fef9c3',
    accentColor: '#a16207'
  },
  {
    id: 'spices',
    name: 'Farm Spices',
    description: 'Aromatic sun-dried whole spices and stone-ground organic condiments.',
    icon: 'Flame',
    itemCount: 12,
    bgLight: '#fee2e2',
    accentColor: '#b91c1c'
  }
];

export const MOCK_FARMERS = [
  {
    id: 'farmer-1',
    name: 'Ramesh Patil',
    farmName: 'Patil Organic Agro Farms',
    location: 'Pune Rural, Maharashtra',
    experienceYears: 18,
    rating: 4.9,
    totalReviews: 240,
    specialty: 'Hydroponic Greens & Vine Tomatoes',
    avatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=250',
    coverImage: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&q=80&w=1200',
    bio: 'Pioneering organic farming in Pune for nearly two decades. We use zero synthetic fertilizers, relying solely on vermicompost and natural rainwater harvesting.'
  },
  {
    id: 'farmer-2',
    name: 'Suresh Kumar',
    farmName: 'Suresh Natural Orchards',
    location: 'Nashik Valley, Maharashtra',
    experienceYears: 12,
    rating: 4.8,
    totalReviews: 185,
    specialty: 'Nashik Red Onions & Table Grapes',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    coverImage: 'https://images.unsplash.com/photo-1592982537447-7440770cbfc9?auto=format&fit=crop&q=80&w=1200',
    bio: 'Dedicated to growing high-yielding, unadulterated root vegetables and seasonal fruits with traditional multi-cropping practices.'
  },
  {
    id: 'farmer-3',
    name: 'Ananya Deshmukh',
    farmName: 'Green Valley Agro Collective',
    location: 'Satara Highlands, Maharashtra',
    experienceYears: 9,
    rating: 4.95,
    totalReviews: 310,
    specialty: 'Heirloom Grains, Millets & Raw Honey',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    coverImage: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=1200',
    bio: 'Leading a women farmers cooperative in Satara preserving ancient indigenous grain varieties with zero pesticide runoff.'
  },
  {
    id: 'farmer-4',
    name: 'Balram Yadav',
    farmName: 'Yadav Fresh Dairy & Cattle Farm',
    location: 'Kolhapur District, Maharashtra',
    experienceYears: 22,
    rating: 4.75,
    totalReviews: 140,
    specialty: 'A2 Gir Cow Milk & Free-Range Country Eggs',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
    coverImage: 'https://images.unsplash.com/photo-1527153857715-3908f2bae5e8?auto=format&fit=crop&q=80&w=1200',
    bio: 'Our indigenous Gir cows roam freely on open green pastures. We bottle whole pure milk within 2 hours of morning milking.'
  }
];

export const MOCK_PRODUCTS = [
  {
    id: 'prod-1',
    name: 'Farm Fresh Organic Tomatoes',
    categoryId: 'vegetables',
    categoryName: 'Fresh Vegetables',
    price: 35,
    originalPrice: 45,
    unit: 'kg',
    farmerId: 'farmer-1',
    farmerName: 'Ramesh Patil',
    farmName: 'Patil Organic Agro Farms',
    location: 'Pune Rural',
    rating: 4.8,
    reviewsCount: 48,
    stock: 120,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Today morning',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=600',
    description: 'Juicy, vine-ripened red tomatoes picked daily at dawn. Grown organically without toxic chemical sprays. Perfect for curries, salads, and fresh purées.',
    nutrition: 'Rich in Lycopene, Vitamin C, Potassium, and Folate.',
    featured: true
  },
  {
    id: 'prod-2',
    name: 'Nashik Quality Red Onions',
    categoryId: 'vegetables',
    categoryName: 'Fresh Vegetables',
    price: 28,
    originalPrice: 35,
    unit: 'kg',
    farmerId: 'farmer-2',
    farmerName: 'Suresh Kumar',
    farmName: 'Suresh Natural Orchards',
    location: 'Nashik Valley',
    rating: 4.7,
    reviewsCount: 64,
    stock: 250,
    status: 'IN_STOCK',
    isOrganic: false,
    harvestDate: '2 days ago',
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&q=80&w=600',
    description: 'Crisp, pungent red onions sourced straight from the heart of Nashik. Well-cured for lasting freshness and authentic aroma in every dish.',
    nutrition: 'High in antioxidants and sulfur-rich quercetin compounds.',
    featured: true
  },
  {
    id: 'prod-3',
    name: 'Mountain Fresh Baby Potatoes',
    categoryId: 'vegetables',
    categoryName: 'Fresh Vegetables',
    price: 32,
    originalPrice: 40,
    unit: 'kg',
    farmerId: 'farmer-1',
    farmerName: 'Ramesh Patil',
    farmName: 'Patil Organic Agro Farms',
    location: 'Pune Rural',
    rating: 4.6,
    reviewsCount: 32,
    stock: 180,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Yesterday',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=600',
    description: 'Naturally firm, golden-skinned organic baby potatoes with a smooth earthy flavor. Great for roasting, dum aloo, and curries.',
    nutrition: 'High fiber, Vitamin B6, and clean natural carbohydrates.',
    featured: false
  },
  {
    id: 'prod-4',
    name: 'Crisp Sweet Orange Carrots',
    categoryId: 'vegetables',
    categoryName: 'Fresh Vegetables',
    price: 45,
    originalPrice: 55,
    unit: 'kg',
    farmerId: 'farmer-2',
    farmerName: 'Suresh Kumar',
    farmName: 'Suresh Natural Orchards',
    location: 'Nashik Valley',
    rating: 4.9,
    reviewsCount: 56,
    stock: 95,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Today morning',
    image: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=600',
    description: 'Tender, naturally sweet organic carrots freshly pulled from moist soil and washed. Enjoy raw in salads or fresh morning juices.',
    nutrition: 'Abundant in Beta-Carotene, Vitamin A, and digestive fiber.',
    featured: true
  },
  {
    id: 'prod-5',
    name: 'Fresh Hydroponic Spinach (Palak)',
    categoryId: 'leafy-greens',
    categoryName: 'Leafy Greens',
    price: 25,
    originalPrice: 30,
    unit: 'bunch',
    farmerId: 'farmer-1',
    farmerName: 'Ramesh Patil',
    farmName: 'Patil Organic Agro Farms',
    location: 'Pune Rural',
    rating: 4.95,
    reviewsCount: 72,
    stock: 50,
    status: 'LOW_STOCK',
    isOrganic: true,
    harvestDate: 'Today morning (5 AM)',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=600',
    description: 'Deep green, tender spinach leaves harvested hours before dispatch. Completely grit-free and grown in nutrient-dense purified water.',
    nutrition: 'Loaded with iron, folate, calcium, and Vitamin K.',
    featured: true
  },
  {
    id: 'prod-6',
    name: 'Organic Purple Brinjals (Eggplant)',
    categoryId: 'vegetables',
    categoryName: 'Fresh Vegetables',
    price: 30,
    originalPrice: 38,
    unit: 'kg',
    farmerId: 'farmer-2',
    farmerName: 'Suresh Kumar',
    farmName: 'Suresh Natural Orchards',
    location: 'Nashik Valley',
    rating: 4.5,
    reviewsCount: 28,
    stock: 80,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Yesterday',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600',
    description: 'Glossy purple, seedless baby brinjals ideal for stuffed bharli vangi and roasted baingan bharta.',
    nutrition: 'Rich in anthocyanins and dietary fiber with low glycemic index.',
    featured: false
  },
  {
    id: 'prod-7',
    name: 'Organic Cavendish Bananas',
    categoryId: 'fruits',
    categoryName: 'Organic Fruits',
    price: 50,
    originalPrice: 60,
    unit: 'dozen',
    farmerId: 'farmer-2',
    farmerName: 'Suresh Kumar',
    farmName: 'Suresh Natural Orchards',
    location: 'Nashik Valley',
    rating: 4.85,
    reviewsCount: 88,
    stock: 140,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Natural tree-ripened',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&q=80&w=600',
    description: 'Chemical-free, carbide-free tree ripened bananas with natural sweetness and soft creamy texture.',
    nutrition: 'Instant energizer packed with Potassium and Vitamin B6.',
    featured: true
  },
  {
    id: 'prod-8',
    name: 'Royal Alphonso Mangoes (Ratnagiri)',
    categoryId: 'fruits',
    categoryName: 'Organic Fruits',
    price: 750,
    originalPrice: 900,
    unit: 'dozen',
    farmerId: 'farmer-3',
    farmerName: 'Ananya Deshmukh',
    farmName: 'Green Valley Agro Collective',
    location: 'Satara Highlands',
    rating: 4.98,
    reviewsCount: 142,
    stock: 35,
    status: 'LOW_STOCK',
    isOrganic: true,
    harvestDate: 'Export grade handpicked',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=600',
    description: 'The King of Mangoes! Authentic GI-tagged Ratnagiri Hapus mangoes, naturally straw-ripened with mesmerizing fragrance and saffron pulp.',
    nutrition: 'Rich in Vitamin A, polyphenols, and prebiotic dietary fiber.',
    featured: true
  },
  {
    id: 'prod-9',
    name: 'Traditional Aged Basmati Rice',
    categoryId: 'grains',
    categoryName: 'Grains & Cereals',
    price: 130,
    originalPrice: 160,
    unit: 'kg',
    farmerId: 'farmer-3',
    farmerName: 'Ananya Deshmukh',
    farmName: 'Green Valley Agro Collective',
    location: 'Satara Highlands',
    rating: 4.9,
    reviewsCount: 95,
    stock: 500,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Aged 18 months',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&q=80&w=600',
    description: 'Long grain, highly aromatic Basmati rice naturally aged for 18 months. Fluffy, non-sticky grains that expand up to twice their length upon cooking.',
    nutrition: 'Gluten-free, clean complex carbs with gentle glycemic load.',
    featured: true
  },
  {
    id: 'prod-10',
    name: 'Pure Raw Forest Blossom Honey',
    categoryId: 'honey-preserves',
    categoryName: 'Raw Honey & Preserves',
    price: 380,
    originalPrice: 450,
    unit: '500g',
    farmerId: 'farmer-3',
    farmerName: 'Ananya Deshmukh',
    farmName: 'Green Valley Agro Collective',
    location: 'Satara Highlands',
    rating: 4.95,
    reviewsCount: 110,
    stock: 45,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Cold-extracted',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=600',
    description: '100% pure raw unprocessed multi-flora forest honey. Never heated or ultra-filtered, retaining all natural pollen, enzymes, and medicinal value.',
    nutrition: 'Natural immunity booster with antibacterial antioxidants.',
    featured: true
  },
  {
    id: 'prod-11',
    name: 'Farm Fresh A2 Gir Cow Milk',
    categoryId: 'dairy-eggs',
    categoryName: 'Dairy & Farm Eggs',
    price: 85,
    originalPrice: 95,
    unit: 'litre',
    farmerId: 'farmer-4',
    farmerName: 'Balram Yadav',
    farmName: 'Yadav Fresh Dairy & Cattle Farm',
    location: 'Kolhapur District',
    rating: 4.92,
    reviewsCount: 160,
    stock: 60,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Milked today at 5:30 AM',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=600',
    description: 'Direct from grass-fed indigenous Gir cows. Unadulterated, unhomogenized whole milk delivered chilled in sterilized glass bottles.',
    nutrition: 'Contains easy-to-digest A2 beta-casein protein and natural calcium.',
    featured: true
  },
  {
    id: 'prod-12',
    name: 'Free-Range Country Hen Eggs (Desi)',
    categoryId: 'dairy-eggs',
    categoryName: 'Dairy & Farm Eggs',
    price: 110,
    originalPrice: 130,
    unit: 'pack of 6',
    farmerId: 'farmer-4',
    farmerName: 'Balram Yadav',
    farmName: 'Yadav Fresh Dairy & Cattle Farm',
    location: 'Kolhapur District',
    rating: 4.88,
    reviewsCount: 78,
    stock: 75,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Fresh daily collection',
    image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?auto=format&fit=crop&q=80&w=600',
    description: 'Farm-fresh brown eggs from free-roaming hens fed a natural grain, herbal, and grass diet. Rich deep orange yolk with high protein content.',
    nutrition: 'Dense in Vitamin D, B12, Choline, and Omega-3 fatty acids.',
    featured: false
  },
  {
    id: 'prod-13',
    name: 'Organic Unpolished Yellow Moong Dal',
    categoryId: 'pulses',
    categoryName: 'Pulses & Legumes',
    price: 145,
    originalPrice: 175,
    unit: 'kg',
    farmerId: 'farmer-3',
    farmerName: 'Ananya Deshmukh',
    farmName: 'Green Valley Agro Collective',
    location: 'Satara Highlands',
    rating: 4.8,
    reviewsCount: 52,
    stock: 160,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Current season crop',
    image: 'https://images.unsplash.com/photo-1585994192701-f1a505c817ea?auto=format&fit=crop&q=80&w=600',
    description: 'Naturally sun-dried and unpolished split moong beans. Retains natural dietary fiber and natural golden sheen without harmful artificial polish.',
    nutrition: '24g protein per 100g, light on digestion, rich in minerals.',
    featured: false
  },
  {
    id: 'prod-14',
    name: 'Fresh Green Pod Peas (Matar)',
    categoryId: 'vegetables',
    categoryName: 'Fresh Vegetables',
    price: 60,
    originalPrice: 75,
    unit: 'kg',
    farmerId: 'farmer-1',
    farmerName: 'Ramesh Patil',
    farmName: 'Patil Organic Agro Farms',
    location: 'Pune Rural',
    rating: 4.75,
    reviewsCount: 38,
    stock: 40,
    status: 'LOW_STOCK',
    isOrganic: true,
    harvestDate: 'Today morning',
    image: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?auto=format&fit=crop&q=80&w=600',
    description: 'Crisp green whole pods packed with plump, naturally sweet green peas. Shelled fresh for curries, pulavs, or snacks.',
    nutrition: 'Loaded with plant protein, Vitamin C, and lutein.',
    featured: false
  },
  {
    id: 'prod-15',
    name: 'Organic Raw Turmeric Finger Root',
    categoryId: 'spices',
    categoryName: 'Farm Spices',
    price: 90,
    originalPrice: 110,
    unit: '500g',
    farmerId: 'farmer-3',
    farmerName: 'Ananya Deshmukh',
    farmName: 'Green Valley Agro Collective',
    location: 'Satara Highlands',
    rating: 4.94,
    reviewsCount: 61,
    stock: 65,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Freshly dug',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&q=80&w=600',
    description: 'Fragrant golden raw turmeric roots rich in natural curcumin oils. Ideal for immune-boosting golden milk, herbal teas, and pickles.',
    nutrition: 'High curcumin concentration (>5%), potent anti-inflammatory.',
    featured: false
  },
  {
    id: 'prod-16',
    name: 'Crisp Kashmiri Red Apples',
    categoryId: 'fruits',
    categoryName: 'Organic Fruits',
    price: 160,
    originalPrice: 190,
    unit: 'kg',
    farmerId: 'farmer-2',
    farmerName: 'Suresh Kumar',
    farmName: 'Suresh Natural Orchards',
    location: 'Nashik Valley',
    rating: 4.9,
    reviewsCount: 84,
    stock: 90,
    status: 'IN_STOCK',
    isOrganic: true,
    harvestDate: 'Handpicked orchard fresh',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=600',
    description: 'Unwaxed, sweet, juicy red apples grown in cool mountain valleys. Naturally crunchy with thin edible skin.',
    nutrition: 'Excellent source of pectin prebiotic fiber and Vitamin C.',
    featured: true
  }
];

export const MOCK_REVIEWS = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    userName: 'Priya Sharma',
    userRole: 'Verified Customer',
    rating: 5,
    date: '3 days ago',
    comment: 'The tomatoes arrived still smelling of fresh vines! Far superior to supermarket produce and kept fresh for over a week in the fridge.'
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    userName: 'Anil Mehta',
    userRole: 'Verified Customer',
    rating: 5,
    date: '1 week ago',
    comment: 'Love knowing exactly which farmer grew my vegetables. Farmer Ramesh Patil is doing incredible work!'
  },
  {
    id: 'rev-3',
    productId: 'prod-8',
    userName: 'Vikram Joshi',
    userRole: 'Verified Customer',
    rating: 5,
    date: '2 days ago',
    comment: 'Unbelievable aroma! True Ratnagiri Alphonso mangoes without any chemical ripening. Will order again next week.'
  },
  {
    id: 'rev-4',
    productId: 'prod-11',
    userName: 'Sunita Deshmukh',
    userRole: 'Verified Customer',
    rating: 5,
    date: 'Yesterday',
    comment: 'The A2 Gir cow milk is thick, sweet, and forms a rich layer of natural cream upon boiling. True authentic village quality.'
  }
];

export const MOCK_STATS = {
  activeFarmers: '500+',
  freshProducts: '2,400+',
  happyFamilies: '18,500+',
  fairPriceGuarantee: '100%'
};
